/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Label = string;
export type Header = {
  [k: string]: unknown;
} & {
  menu: Menu;
  left?: HeaderSection;
  centre?: HeaderSection;
  right?: HeaderSection;
  contentWidth?: ContentWidth;
  /**
   * Whether to display the header.
   */
  visible?: boolean;
};
export type ID = string;
export type HREF = string;
export type Menu = {
  id: ID;
  label: Label;
  href: HREF;
}[];
export type HeaderSection =
  | {
      type?: "logo";
      [k: string]: unknown;
    }
  | {
      type?: "menu";
      menu: ID[];
      [k: string]: unknown;
    };
export type ContentWidth = "full" | "contained";
export type Section = Hero;
export type Hero = {
  type: "hero";
} & (StandardHero | CarouselHero);
export type StandardHero = BaseHero & {
  variant: "standard";
};

/**
 * The schema for a Bare Site.
 */
export interface BareSite {
  /**
   * The version of the Bare Site schema used by this site.
   */
  schemaVersion: 1;
  name: Label;
  /**
   * A short description of the site.
   */
  description?: string;
  template: BareTemplate;
  theme: BareTheme;
}
/**
 * The schema for a Bare Site template.
 */
export interface BareTemplate {
  /**
   * The version of the Bare Site template schema used by this template
   */
  schemaVersion: 1;
  layout: Layout;
  /**
   * @minItems 1
   */
  pages: [Page, ...Page[]];
}
export interface Layout {
  header: Header;
  footer: Footer;
  contentWidth?: ContentWidth;
}
export interface Footer {
  /**
   * Whether to display the footer.
   */
  visible?: boolean;
  contentWidth?: ContentWidth;
}
export interface Page {
  /**
   * The route of the page.
   */
  route: string;
  title: Label;
  sections: Section[];
}
export interface BaseHero {
  image: string;
  heading: string;
  subheading?: string;
  actions?: Action[];
}
export interface Action {
  label: Label;
  href: HREF;
}
export interface CarouselHero {
  variant: "carousel";
  pages: BaseHero[];
}
/**
 * The schema for a Bare Site theme.
 */
export interface BareTheme {
  /**
   * The version of the Bare Site theme schema used by this theme.
   */
  schemaVersion: 1;
  colours: Colours;
  typography: Typography;
  /**
   * The overall spacing density of the site.
   */
  spacing: "tight" | "comfortable" | "spacious";
  /**
   * The overall shape language of the site.
   */
  shape: "sharp" | "soft" | "rounded";
}
export interface Colours {
  /**
   * The main colour of your brand.
   */
  primary: string;
  /**
   * Foreground colour to use with the primary colour.
   */
  primaryContent: string;
  /**
   * The optional, secondary colour of your brand.
   */
  secondary?: string;
  /**
   * Foreground colour to use with the secondary colour.
   */
  secondaryContent?: string;
  /**
   * The optional, accent colour of your brand.
   */
  accent?: string;
  /**
   * Foreground colour to use with the accent color.
   */
  accentContent?: string;
  /**
   * A neutral dark colour.
   */
  neutral: string;
  /**
   * Foreground colour to use with the neutral color.
   */
  neutralContent: string;
  /**
   * Base surface colour.
   */
  base1: string;
  /**
   * Darker base colour.
   */
  base2: string;
  /**
   * Darkest base colour.
   */
  base3: string;
  /**
   * Foreground colour to use with the base colours.
   */
  baseContent: string;
  /**
   * Info colour.
   */
  info: string;
  /**
   * Foreground colour to use with the info colour.
   */
  infoContent: string;
  /**
   * Success colour.
   */
  success: string;
  /**
   * Foreground colour to use with the success colour.
   */
  successContent: string;
  /**
   * Warning colour.
   */
  warning: string;
  /**
   * Foreground colour to use with the warning colour.
   */
  warningContent: string;
  /**
   * Error colour.
   */
  error: string;
  /**
   * Foreground colour to use with the error colour.
   */
  errorContent: string;
  [k: string]: unknown;
}
export interface Typography {
  /**
   * The primary font used for headings.
   */
  heading: string;
  /**
   * The primary font used for body text.
   */
  body: string;
  [k: string]: unknown;
}
